*** Variables ***
# Modules in Auth
${PACKAGE_INFO_AUTH}                    packageInfoPermission
${DEVICE_AUTH}                          deviceInfoPermission
${DEVICE_POLICY_AUTH}                   devicePolicyPermission
${PACKAGE_POLICY_AUTH}                  packagePolicyPermission

# Values in Auth
${EDITABLE_AUTH}                        Editable
${READ_ONLY_AUTH}                       Read Only
${NONE_AUTH}                            None

